languageCode = "fr"
languageName = "Français"
languageDirection = "ltr"
weight = 1

title = "Rodrigue Govan"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[params.author]
  name = "Rodrigue Govan"
  image = "rodrigue-govan.jpg"
  headline = "Docteur en Informatique"
  #bio = "Lorem ipsum"
  links = [
     { email = "mailto:rodrigue.govan@unc.nc" },
  #   { link = "https://rodrigueg.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
     { github = "https://github.com/rodrigueg" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
     { google-scholar = "https://scholar.google.com/citations?user=4Zji-pgAAAAJ&hl=fr&oi=ao" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { instagram = "https://instagram.com/rodrigueg" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
     { linkedin = "https://linkedin.com/in/rodrigueg" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { mendeley = "https://www.mendeley.com/" },
  #   { microsoft = "https://www.microsoft.com/" },
     { orcid = "https://orcid.org/0000-0002-4087-7056" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
     { researchgate = "https://www.researchgate.net/profile/Rodrigue-Govan" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { threads = "https://threads.net/@username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { x-twitter = "https://twitter.com/username" },
  #   { youtube = "https://youtube.com/username" },
   ]
