name: Unlabeller

on:
  issues:
    types: [closed]
  pull_request:
    types: [closed]

jobs:
  unlabel:
    runs-on: [self-hosted, pi5-8gb]
    steps:
      - name: Remove labels
        uses: andymckay/labeler@master
        with:
          remove-labels: "wip"
